routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/delete-all', 'PostsController@deleteAll')->name('deleteall');
Route::delete('/delete-all', 'PostsController@deleteAll');

Route::get('/', 'PostsController@index')->name('index');
Route::resource('/comments', 'PostsController', ['except' => ['index', 'create', 'show']]);

Auth::routes();

Route::get('/user/{id}', 'PostsController@showUsersPosts')->name('usersPosts');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{   
    protected $fillable = ['name', 'user_id', 'text', 'created', 'edited'];

    public $timestamps = false;

    public function user()
    {
    	return $this->belongsTo('App\User');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts()
    {
        return $this->hasMany('App\Post');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use Validator;
use App\Post;
use App\User;
use App\Classes\CookieSetter;
use App\Http\Requests\PostRequest;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user_id = Auth::user()->id ?? '';
        $msgStatus = $request->session()->pull('msg');
        $data = Post::orderBy('id', 'desc')->paginate(5);
        return view('index', compact('data', 'msgStatus', 'user_id'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        $data = $request->except('_token');
        $data['created'] = date('d.m.Y H:i');
        $data['user_id'] = Auth::user()->id;

        foreach($data as $key => $item) {
            $data[$key] = nl2br(htmlspecialchars($item));
        }       

        if(Post::create($data)) {
            return redirect()->route('index')->with('msg', 'Комментарий успешно добавлен');
        } else {
            return redirect()->route('index')->with('msg', 'Неопознанная ошибка');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        $request->session()->put('pageurl', $request->server('HTTP_REFERER'));
        $user = Auth::user()->name ?? '';
        $data = Post::where('id', $id)->first();
        $data->text = strip_tags($data->text);

        return view('edit', compact('data', 'user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, $id)
    {
        $url = $request->session()->pull('pageurl') ?? route('index');
        $data = $request->except('_token', '_method');
        $data['edited'] = date('d.m.Y H:i');

        foreach($data as $key => $item) {
            $data[$key] = nl2br(htmlspecialchars($item));
        }
        if(Post::where('id', $id)->update($data)){
            return redirect($url)->with('msg', 'Запись успешно изменена');
        } else {
            return redirect()->route('index')->with('msg', 'Неопознанная ошибка');
            }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {           
                if(Post::where('id', $id)->delete()) {
                return back()->with('msg', 'Запись успешно удалена');
        } else {
                return redirect()->route($url)->with('msg', 'Неопознанная ошибка');

        }
    }

            public function deleteAll(Request $request)
        {   
            if($request->isMethod('GET')) {
                $user = Auth::user()->name ?? '';
                return view('doyouwant', compact('user'));
            } elseif($request->isMethod('DELETE')) {
                Post::where('id', '>', 0)->delete();

                return redirect()->route('index')->with('msg', 'Все записи успешно удалены');
            }
        }

        public function showUsersPosts(Request $request, $id)
        {  
            $user_id = Auth::user()->id ?? '';
            $msgStatus = $request->session()->pull('msg');
            $user = User::find($id);
            $data = $user->posts()->orderBy('id', 'desc')->paginate(5);
            return view('index', compact('data', 'msgStatus', 'user_id'));
        }
}

resources/views/admin/login.blade.php
@extends('layout')

@section('content')

@endsection

@section('form')
  <div class="container">
    <label for="exampleFormControlInput1"><font color="grey">Вход</font></label>
<form method="POST" action="/admin">
  @csrf
  <div class="form-group">
    <label for="exampleFormControlInput1">Имя</label>
    <input type="text" class="form-control" id="exampleFormControlInput1" name="name">
  </div>
    <div class="form-group">
    <label for="exampleFormControlInput1">Пароль</label>
    <input type="password" class="form-control" id="exampleFormControlInput1" name="pass">
  </div>
   <input type="submit" class="btn btn-primary" value="Добавить">
</form>
</div>
@endsection

resources/views/block.blade.php
<div class="card-header">
       <font class="name_author"><a href="{{ route('usersPosts', ['id' => $post->user->id]) }}">{!! $post->user->name !!}</a></font> <font color='gray'>{!! $post->created !!}</font>
       @if(session('status') == 2)
       <font color="grey"><a href="mailto:{{ $post->email }}">{{ $post->user->email }}</a></font>
       @endif
      </div>
      <div class="card-body">

          <p>{!! $post->text !!}</p>

 @if(session('status') == 2 || $user_id == $post->user->id)         



<div class="row">
     <div>
<form action="{{ route('comments.destroy', ['comment' => $post->id]) }}" method="POST">
@csrf{{ method_field('DELETE') }}
<input class="btn btn-link edited-link" type="submit" value="удалить">
</form></div> 
<div>
<form action="{{ route('comments.edit', ['comment' => $post->id]) }}" method="POST">
@csrf{{ method_field('GET') }}
<input class="btn btn-link edited-link" type="submit" value="изменить">
</form></div>

</div>


@endif

 </div>

resources/views/doyouwant.blade.php
@extends('layout')

@section('content')

@endsection

@section('form')
  <div class="container">

  <label for="exampleFormControlInput1"><b>Вы уверены, что хотите удалить все записи из Гостевой книги?<br>То, что случится, уже не вернуть...</b></label>
  <div class="container">
<div class="row">
    <div class="col-xs-2 border col-xs-offset-4">
<form method="POST">
	  @csrf
{{ method_field('DELETE') }}
<input class="btn btn-outline-danger" type="submit" value="Да">
</form>
    </div>
    <div class="col-xs-2"> </div>
    <div class="col-xs-2"><a class="btn btn-outline-primary" href="{{ route('index') }}">Нет</a></div>
</div>
</div>

  </div>
@endsection

resources/views/edit.blade.php
@extends('layout')

@section('content')

@endsection

@section('form')
  <div class="container">
    <label for="exampleFormControlInput1"><font color="grey">Редактировать комментарий</font></label>
<form action="{{ route('comments.update', ['comment' => $data->id]) }}" method="POST">
	  @csrf
{{ method_field('PUT') }}
  <div class="form-group">
    <textarea class="form-control" id="exampleFormControlTextarea1" name="text" rows="5">{!! $data->text !!}</textarea>
  </div>
   <input type="submit" class="btn btn-primary" value="Изменить">
</form>
</div>
@endsection

resources/views/error.blade.php
<a name="errors"></a>
<div class="container">
<div class="alert alert-danger" role="alert">
  <ul>
 @foreach($errors->all() as $error)
<li>{{ $error }}</li>
@endforeach
  </ul>
</div>
</div>

resources/views/form.blade.php
@if(session('status') > 0)
  <div class="container">
    <label for="exampleFormControlInput1"><font color="grey">Добавить комментарий</font></label>
<form method="POST" action="{{ route('comments.store') }}">
  @csrf
  <div class="form-group">
    <textarea class="form-control" id="exampleFormControlTextarea1" name="text" rows="5">{{ old('text') }}</textarea>
  </div>
   <input type="submit" class="btn btn-primary" value="Добавить">
</form>
</div>
@else
  <div class="container">
    <label for="exampleFormControlInput1"><a href="{{ route('login') }}">Войдите</a>, чтобы оставить комментарий или <a href="{{ route('register') }}">зарегистрируйтесь</a>.</font></label>
</div>
@endif

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layout')

@section('content')
@if(count($data) > 0)
<div class="container">
  <div class="card-deck mb-3">
    <div class="card mb-4 shadow-sm">
    	
	    	@foreach($data as $post)
			@include('block')
			@endforeach
    </div>
    </div>
  </div>
  <div class="container">
      {{ $data->links() }}
  </div>
@else
@include('notposts');
@endif
 @endsection

resources/views/layout.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Pricing example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/pricing/">

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="/style.css" rel="stylesheet">
  </head>
  <body>
    @include('nav')

    @if(!empty($msgStatus) == TRUE)
    @include('success')
    @endif

    @yield('content')

    @if(count($errors->all()) > 0)
    @include('error')
    @endif

@section('form')
@include('form')
@show

  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
        <small class="d-block mb-3 text-muted">&copy; 2017-2019</small>
      </div>
      
    </div>
  </footer>
</div>
</body>
</html>

resources/views/nav.blade.php
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal"><a href="/">Гостевая книга</a></h5>

  <nav class="my-2 my-md-0 mr-md-3">
@if(session('status') == 0)
<a class="btn btn-outline-primary" href="{{ route('login') }}">Вход</a>
<a class="btn btn-outline-primary" href="{{ route('register') }}">Регистрация</a>
@endif

@if(session('status') >= 1)
 <font color='gray'>{{ session('user') }}</font> 
@endif

@if(session('status') == 2)
  <a class="btn btn-outline-danger" href="{{ route('deleteall') }}">Очистить комментарии</a>
@endif

   </nav>

 @if(session('status') >= 1)
 <form method="POST" action="{{ route('logout') }}">
 	@csrf
  <input type="submit" class="btn btn-outline-primary" value="Выйти">
</form>
@endif
</div>

resources/views/notposts.blade.php
<div class="container">
<div class="alert alert-primary" role="alert">
<p>Записей пока нет</p>
</div>
</div>

resources/views/success.blade.php
<div class="container">
<div class="alert alert-success" role="alert">
  <ul>
<li>{{ $msgStatus }}</li>
  </ul>
</div>
</div>